'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace EjSuite.Modules.EjSuite

    Partial Public Class ProductoStockActual

        '''<summary>
        '''upPanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upPanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''plProductoid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plProductoid As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProducto As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''prcProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents prcProducto As Global.EjSuite.Modules.EjSuite.ProductoControl

        '''<summary>
        '''hfProductoId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfProductoId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''plStockActualProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStockActualProducto As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblStockActualProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStockActualProducto As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
