'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace EjSuite.Modules.EjSuite

    Partial Public Class ProductoControlSearch

        '''<summary>
        '''upPanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upPanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''txt1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''prcProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents prcProducto As Global.EjSuite.Modules.EjSuite.ProductoControl
    End Class
End Namespace
