'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace EjSuite.Modules.EjSuite

    Partial Public Class ProductoPrecioBase

        '''<summary>
        '''upPanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upPanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''plProductoidLote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plProductoidLote As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProducto As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ProductoControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductoControl1 As Global.EjSuite.Modules.EjSuite.ProductoControl

        '''<summary>
        '''hfProductoId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfProductoId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''plPrecioanteriorenvaseLote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPrecioanteriorenvaseLote As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPrecioanteriorenvaseLote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrecioanteriorenvaseLote As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
